module Dados where

-- http://www.wjr.eti.br/nameGenerator/

nomes = [
  "Abigail Francia",
  "Abigail Malta",
  "Abraao Ourique",
  "Adelina Dourado",
  "Adriana Camello",
  "Aderito Curvelo",
  "Aida Canedo",
  "Aires Paranhos",
  "Aires Villas Boas",
  "Alarico Bastos",
  "Alberta Lagos",
  "Alberto Meneses",
  "Albino Corte-Real",
  "Albino Quirino",
  "Alceste Valentin",
  "Aldonca Nascimento",
  "Alfredo Gonsalves",
  "Alicia Freitas",
  "Amalia Castillo",
  "Americo Grillo",
  "Ana Cambezes",
  "Anabela Marroquim",
  "Anabela Paranhos",
  "Andreoleto Ornellas",
  "Andreoleto Reyes",
  "Andreoleto Verguero",
  "Angelina Cabrera",
  "Angelina Tristao",
  "Angelino Goncalves",
  "Angelico Eanes",
  "Anita Quintais",
  "Anselmo Ferrera",
  "Antero Cascaes",
  "Apua Jaguaribe",
  "Arachane Capistrano",
  "Arachane Parracho",
  "Artur Duran",
  "Aurelia Feijo",
  "Basilio Verguero",
  "Bernardete Pitangui",
  "Bernardina Passos",
  "Branca Coimbra",
  "Brenda Tavora",
  "Bruno Martins",
  "Bras Natal",
  "Caetano Jesus",
  "Capitolina Mendoca",
  "Carmem Cayubi",
  "Cassandra Villaca",
  "Celestino Tabalipa",
  "Claudia Aragon",
  "Claudio Ornellas",
  "Clovis Luz",
  "Constanca Loio",
  "Cosme Bastos",
  "Cosperranho Trindade",
  "Crispim Maia",
  "Cristovao Alencastre",
  "Daniel Silvera",
  "Deise Malheiro",
  "Denise Portella",
  "Deolindo Carrasqueira",
  "Dinarte Cidreira",
  "Dinarte Correa",
  "Dino Lages",
  "Dionisio Gimenez",
  "Dirceu Guarabira",
  "Diogenes Acores",
  "Dulce Freyria",
  "Dalia Lencastre",
  "Edite Gaspar",
  "Egas Alburquerque",
  "Elisa Guimaraens",
  "Ema Bernardes",
  "Ema Godoi",
  "Emiliano Natal",
  "Enilda Passos",
  "Epaminondas Saloio",
  "Ermelinda Belchiorinho",
  "Ermelinda Lagos",
  "Esmeralda Salvado",
  "Eugenia Veloso",
  "Eusebio Marino",
  "Evaristo Quintal",
  "Evaristo Villegas",
  "Filipe Rocha",
  "Firmina Vasconcelos",
  "Firmino Frois",
  "Flaminia Mourinho",
  "Flor Lopez",
  "Florinda Castelao",
  "Flavio Losada",
  "Fabia Porciuncula",
  "Gabriel Noite",
  "Galindo Alancastre",
  "Gaspar Pinho",
  "Gaudencio Torcuato",
  "Gedeao Modesto",
  "Gedeao Paula",
  "Gedeao Talhao",
  "Genoveva Silveira dos Acores",
  "Geraldo Pereira",
  "Gerson Baptista",
  "Gina Taveira",
  "Godo Barboza",
  "Gomes Beltran",
  "Guadalupe Castilho",
  "Gustavo Antas",
  "Henrique Robalinho",
  "Heriberto Moreno",
  "Heriberto Vila-Cha",
  "Honorina Beiriz",
  "Ibere Eiro",
  "Ilduara Cayubi",
  "Ilidio Belchior",
  "Inacio Canica",
  "Ines Monforte",
  "Isabel Pimenta",
  "Isaura Alcantara",
  "Itibere Ochoa",
  "Jaci Fidalgo",
  "Jacinta Gutierrez",
  "Jacinto Lagoa",
  "Jadir Infante",
  "Jadir Simoes",
  "Janaina Pitanga",
  "Jandira Resende",
  "Jucara Baiao",
  "Jonatas Miranda",
  "Laura Campos",
  "Lais Leite",
  "Leonardo Quintella",
  "Leticia Barrocas",
  "Levi Robalo",
  "Luana Freire",
  "Lurdes Higuera",
  "Luis Bahia",
  "Lazaro Freire",
  "Lidia Neres",
  "Lucia Muniz",
  "Mara Andrade",
  "Marco Beltrao",
  "Mariana Velasquez",
  "Marisa Cortes",
  "Marlene Boga",
  "Martinho Acevedo",
  "Mauro Ulhoa",
  "Melissa Ferro",
  "Melissa Sucupira",
  "Mercedes Correa",
  "Mercedes Reino",
  "Miguelina Goulart",
  "Mileide Carreira",
  "Miru Muñiz",
  "Marcio Araujo",
  "Maxima Buenaventura",
  "Mecia Barcelos",
  "Norberto Moreno",
  "Noemia Pessanha",
  "Nuno Barra",
  "Odilia Camillo",
  "Olga Pestana",
  "Olivio Camacho",
  "Orestes Vilanova",
  "Pascoal Rebimbas",
  "Patricia Novalles",
  "Patricio Garcia",
  "Paulino Miguel",
  "Penelope Sequera",
  "Polibe Vilaca",
  "Querubim Pontes",
  "Quintiliano Garrau",
  "Quintilien Braganca",
  "Quirina Bivar",
  "Quirina Padua",
  "Quirina Tabosa",
  "Quirino Piñero",
  "Quiteria Valentin",
  "Quiterio Camillo",
  "Rafael Benavides",
  "Rafaela Aragao",
  "Rafaela Castillo",
  "Raquel Morales",
  "Rebeca Paes",
  "Regina Osorio",
  "Regina Rodovalho",
  "Remo Machado",
  "Remo Otero",
  "Ricardo Guerra",
  "Roberto Rabelo",
  "Rodolfo Batata",
  "Rodrigo Xavier",
  "Ronaldo Clementino",
  "Rosalina Cardim",
  "Rosalinda Guerra",
  "Rosaura Malta",
  "Rosario Ruas",
  "Rubim Freyria",
  "Rui Leao",
  "Salomao Cyrne",
  "Salomao Farias",
  "Salvina Caminha",
  "Samuel Correa",
  "Sandoval Barroso",
  "Sandoval Salguero",
  "Sebastiana Bastos",
  "Sebastiana Frade",
  "Sebastiao Cidreira",
  "Severino Regalado",
  "Simeao Robalo",
  "Siquenique Capiperibe",
  "Soeiro Silva",
  "Solange Parracho",
  "Solano Barrocas",
  "Soraia Faro",
  "Sergio Collaco",
  "Sergio Higuera",
  "Sergio Sosa",
  "Sergio Varanda",
  "Sonia Cordeiro",
  "Tatiana Fuentes",
  "Telmo Villalobos",
  "Teodoro Semedo",
  "Tiburcio Morais",
  "Ubajara Prates",
  "Ubajara Sequeira",
  "Ubaldo Faia",
  "Ulisses Prudente",
  "Urania Casquero",
  "Urania Mansilha",
  "Valentim Salazar",
  "Valeria Pinho",
  "Valerio Pequeno",
  "Vanda Capucho",
  "Verissimo Botelho",
  "Vicente Valim",
  "Vania Aranha",
  "Ximeno Marino",
  "Xenia Corte-Real",
  "Zeferino Carvalhoso",
  "Zuleide Ochoa",
  "Zelia Alcantara",
  "Zozimo Bugallo",
  "Zozimo Gama",
  "Zozimo Moutinho",
  "atila Inacio",
  "angela Castelo Branco",
  "enia Cafe",
  "enia Leon",
  "erica Gira"]


marcas = ["Lamborghini",
  "Morgan",
  "Mazda",
  "Volvo",
  "Aston Martin",
  "Renault",
  "Koenigsegg",
  "Chrysler",
  "Suzuki",
  "Mercedes-Benz",
  "Hummer",
  "Abarth",
  "Kia",
  "Dodge",
  "Chevrolet",
  "McLaren",
  "Audi",
  "Maserati",
  "Pagani",
  "Noble",
  "Caterham",
  "Citroen",
  "VW",
  "Lotus",
  "BMW",
  "Rolls-Royce",
  "Jeep",
  "Daihatsu",
  "Honda",
  "Hyundai",
  "KTM",
  "Alfa Romeo",
  "Seat",
  "Mitsubishi",
  "Proton",
  "Maybach",
  "Land Rover",
  "Gordon Murray",
  "Porsche",
  "Tesla Motors"]