/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 16 19:56:16 GMT 2020
 */

package utils;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import carros.Coordinate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockGregorianCalendar;
import org.junit.runner.RunWith;
import utilizadores.Cliente;
import utils.ComparadorKm;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ComparadorKm_ESTest extends utils.ComparadorKm_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ComparadorKm comparadorKm0 = new ComparadorKm();
      Cliente cliente0 = new Cliente();
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar(0, 0, (-1), 0, (-3220));
      Coordinate coordinate0 = new Coordinate((-4719.893), 1.0);
      Cliente cliente1 = new Cliente("", "", "5MiDpqUv$v*", "5MiDpqUv$v*", "", mockGregorianCalendar0, coordinate0, 1, 0, (-4719.893));
      int int0 = comparadorKm0.compare(cliente0, cliente1);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ComparadorKm comparadorKm0 = new ComparadorKm();
      // Undeclared exception!
      try { 
        comparadorKm0.compare((Cliente) null, (Cliente) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("utils.ComparadorKm", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ComparadorKm comparadorKm0 = new ComparadorKm();
      Cliente cliente0 = new Cliente();
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar(3115, (-1), 3115);
      Coordinate coordinate0 = new Coordinate((-1.0), (-1));
      Cliente cliente1 = new Cliente("", "", "", "", "", mockGregorianCalendar0, coordinate0, 1, (-1), (-1));
      int int0 = comparadorKm0.compare(cliente1, cliente0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ComparadorKm comparadorKm0 = new ComparadorKm();
      Cliente cliente0 = new Cliente();
      int int0 = comparadorKm0.compare(cliente0, cliente0);
      assertEquals((-1), int0);
  }
}
